### ISSUE TITLE
Red State and Orange State

### ISSUE THREAD

**Issue by Romz24** [defvs/android_device_umidigi_f2#5]
I reflashed the phone with this recovery. When I try to enter it, I get an error. Can you describe the installation instructions?

```
Red State
Your device has failed the verification and may not work properly.
Please download boot image with correct signature or disable verified boot.
Your device will reboot in 5 seconds...
```

**Comment by Romz24** [comment]
I partially figured out what the past error was, I unlocked the bootloader but now I get an endless reboot of the phone when I turn it on or when I try to enter the TWRP. I tried several times to reinstall the recovery, I even completely flashed the phone, but this does not give any results. When I return the old recovery, the phone turns on without problems.

```
Orange State
Your devices has been unlocked and can't be trusted
Your devices will boot in 5 seconds
```

ROM: UMIDIGI_F2_V1.0_20200116.V3.09

**Comment by defvs** [comment]
Please read the instructions provided in the XDA Thread concerning flashing magisk. This is not the place for this kind of issues as the recovery has nothing to do with you not booting.

To answer your question and if you really are this lazy, do these commands in Bootloader mode (adb reboot bootloader).
fastboot flashing unlock
fastboot flashing unlock_critical
fastboot --disable-verity --disable-verification flash boot boot.img
fastboot --disable-verity --disable-verification flash recovery (twrp).img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img

**Comment by defvs** [comment]
XDA Thread here https://forum.xda-developers.com/android/development/guide-rooting-umidigi-f2-t4030407 please do not use this repo for your issues concerning bootloops as the recovery is working fine. Let's continue the discussion there please ! 😄
